# Form implementation generated from reading ui file 'newgui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(416, 415)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 20, 141, 16))
        self.label.setObjectName("label")
        self.predictRadioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.predictRadioButton.setGeometry(QtCore.QRect(100, 90, 81, 20))
        self.predictRadioButton.setObjectName("predictRadioButton")
        self.historicalRadioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.historicalRadioButton.setGeometry(QtCore.QRect(250, 90, 100, 20))
        self.historicalRadioButton.setObjectName("historicalRadioButton")
        self.inputField = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputField.setGeometry(QtCore.QRect(200, 50, 113, 21))
        self.inputField.setObjectName("inputField")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 131, 20))
        self.label_2.setObjectName("label_2")
        self.outputLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(50, 140, 331, 161))
        self.outputLabel.setText("")
        self.outputLabel.setObjectName("outputLabel")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 340, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 340, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Stock Market App"))
        self.predictRadioButton.setText(_translate("MainWindow", "Low"))
        self.historicalRadioButton.setText(_translate("MainWindow", "High"))
        self.label_2.setText(_translate("MainWindow", "Enter a stock ticker:"))
        self.pushButton.setText(_translate("MainWindow", "ENTER"))
        self.pushButton_2.setText(_translate("MainWindow", "CLEAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
